# Generated by Django 4.2.7 on 2023-12-22 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='autor',
        ),
    ]
